[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npx tsx src/server.ts"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"